[package]
name = "roadmap_sh_github_user_activity"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[[bin]]
name = "github-activity-cli"           # 👈 This is the CLI binary name
path = "src/main.rs"